## Problem1

Here is the time series data [110,125,133,146,158,172,187,196,210]. Build an RNN/LSTM model to predict the next 10 digits

### Samples

We can divide the sequence into multiple input/output patterns called samples, where three time steps are used as input and one time step is used as output for the one-step prediction that is being learned.

In [18]:
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [19]:
## define input sequence
raw_seq = [110,125,133,146,158,172,187,196,210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[110 125 133] 146
[125 133 146] 158
[133 146 158] 172
[146 158 172] 187
[158 172 187] 196
[172 187 196] 210


### Develop LSTM model

In [23]:
X.reshape((X.shape[0], X.shape[1], 1))


array([[[110],
        [125],
        [133]],

       [[125],
        [133],
        [146]],

       [[133],
        [146],
        [158]],

       [[146],
        [158],
        [172]],

       [[158],
        [172],
        [187]],

       [[172],
        [187],
        [196]]])

In [24]:
# univariate lstm example
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [25]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [26]:
# demonstrate prediction
x_input = array([187,196,210])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[231.04669]]
