## Problem2

Divide the diabetes data into train and test datasets and build a Random Forest and Decision Tree model with Outcome as the output variable. 

In [40]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('Diabetes.csv')
data.isnull().sum()

 Number of times pregnant        0
 Plasma glucose concentration    0
 Diastolic blood pressure        0
 Triceps skin fold thickness     0
 2-Hour serum insulin            0
 Body mass index                 0
 Diabetes pedigree function      0
 Age (years)                     0
 Class variable                  0
dtype: int64

In [41]:
data.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0    Number of times pregnant      768 non-null    int64  
 1    Plasma glucose concentration  768 non-null    int64  
 2    Diastolic blood pressure      768 non-null    int64  
 3    Triceps skin fold thickness   768 non-null    int64  
 4    2-Hour serum insulin          768 non-null    int64  
 5    Body mass index               768 non-null    float64
 6    Diabetes pedigree function    768 non-null    float64
 7    Age (years)                   768 non-null    int64  
 8    Class variable                768 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB


In [43]:
data.shape

(768, 9)

In [44]:
data.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [45]:
data.rename(columns = {' Class variable':'result'}, inplace = True)

In [46]:
data.columns

Index([' Number of times pregnant', ' Plasma glucose concentration',
       ' Diastolic blood pressure', ' Triceps skin fold thickness',
       ' 2-Hour serum insulin', ' Body mass index',
       ' Diabetes pedigree function', ' Age (years)', 'result'],
      dtype='object')

In [47]:
# We need to encode Class variable
lb = LabelEncoder()
data['result'] = lb.fit_transform(data['result'])

In [48]:
data.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  result  
0            50       1  
1            31       0  
2            32       1  
3            21       0  
4            33       1

In [49]:
data.dtypes

 Number of times pregnant          int64
 Plasma glucose concentration      int64
 Diastolic blood pressure          int64
 Triceps skin fold thickness       int64
 2-Hour serum insulin              int64
 Body mass index                 float64
 Diabetes pedigree function      float64
 Age (years)                       int64
result                             int32
dtype: object

In [50]:
# no zero variance
data.var()

 Number of times pregnant           11.354056
 Plasma glucose concentration     1022.248314
 Diastolic blood pressure          374.647271
 Triceps skin fold thickness       254.473245
 2-Hour serum insulin            13281.180078
 Body mass index                    62.159984
 Diabetes pedigree function          0.109779
 Age (years)                       138.303046
result                               0.227483
dtype: float64

In [51]:
colnames = list(data.columns)
predictors = colnames[:8]
target = colnames[8]

In [52]:
predictors

[' Number of times pregnant',
 ' Plasma glucose concentration',
 ' Diastolic blood pressure',
 ' Triceps skin fold thickness',
 ' 2-Hour serum insulin',
 ' Body mass index',
 ' Diabetes pedigree function',
 ' Age (years)']

In [53]:
target

'result'

In [54]:
# Splitting data into training and testing data set
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3)

In [55]:
from sklearn.tree import DecisionTreeClassifier as DT
model = DT(criterion = 'entropy')
model.fit(train[predictors], train[target])

DecisionTreeClassifier(criterion='entropy')

In [56]:
# Prediction on Test Data
preds = model.predict(test[predictors])
pd.crosstab(test[target], preds, rownames=['Actual'], colnames=['Predictions'])


Predictions    0   1
Actual              
0            118  31
1             39  43

In [57]:
np.mean(preds == test[target]) # Test Data Accuracy 

0.696969696969697

In [58]:
# Print the confusion matrix (alternate way)
from sklearn import metrics
metrics.confusion_matrix(test[target], preds)

array([[118,  31],
       [ 39,  43]], dtype=int64)

In [59]:
# Print the precision and recall, for all 2 classes
print(metrics.classification_report(test[target], preds, digits=2))

              precision    recall  f1-score   support

           0       0.75      0.79      0.77       149
           1       0.58      0.52      0.55        82

    accuracy                           0.70       231
   macro avg       0.67      0.66      0.66       231
weighted avg       0.69      0.70      0.69       231



In [60]:
# Prediction on Train Data
preds = model.predict(train[predictors])
pd.crosstab(train[target], preds, rownames = ['Actual'], colnames = ['Predictions'])

Predictions    0    1
Actual               
0            351    0
1              0  186

In [61]:
np.mean(preds == train[target]) # Train Data Accuracy

1.0

In [62]:
# Print the confusion matrix (alternate way)
from sklearn import metrics
metrics.confusion_matrix(train[target], preds)

array([[351,   0],
       [  0, 186]], dtype=int64)

In [63]:
# Print the precision and recall, for all 2 classes
print(metrics.classification_report(train[target], preds, digits=2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       351
           1       1.00      1.00      1.00       186

    accuracy                           1.00       537
   macro avg       1.00      1.00      1.00       537
weighted avg       1.00      1.00      1.00       537



In [64]:
# Building  Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion = 'entropy', random_state = 42)
rfc.fit(train[predictors], train[target])

RandomForestClassifier(criterion='entropy', random_state=42)

In [65]:
# Evaluating on Training set
rfc_pred_train = rfc.predict(train[predictors])
metrics.confusion_matrix(train[target], rfc_pred_train)

array([[351,   0],
       [  0, 186]], dtype=int64)

In [66]:
# Print the precision and recall and f1 score, for all 3 classes
print(metrics.classification_report(train[target], rfc_pred_train, digits=2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       351
           1       1.00      1.00      1.00       186

    accuracy                           1.00       537
   macro avg       1.00      1.00      1.00       537
weighted avg       1.00      1.00      1.00       537



In [67]:
# Evaluating on Test set
rfc_pred_test = rfc.predict(test[predictors])
metrics.confusion_matrix(test[target], rfc_pred_test)

array([[125,  24],
       [ 40,  42]], dtype=int64)

In [68]:
# Print the precision and recall and f1 score, for all 3 classes
print(metrics.classification_report(test[target], rfc_pred_test, digits=2))

              precision    recall  f1-score   support

           0       0.76      0.84      0.80       149
           1       0.64      0.51      0.57        82

    accuracy                           0.72       231
   macro avg       0.70      0.68      0.68       231
weighted avg       0.71      0.72      0.72       231

